server:
  port: 7080
zuul:
  routes:
    aqi:
      path: /aqi-service/**
      url: http://localhost:8080
    bot:
      path: /bot/**
      url: http://localhost:3000
ribbon:
  eureka:
    enabled: false
---
spring:
  profiles: container
server:
  port: ${APP_PORT:7080}
zuul:
  routes:
    aqi:
      path: /aqi-service/**
      url: http://aqi-service:80
    bot:
      path: /bot/**
      url: http://aqi-bot:80